// TIS territory containment — the full CISAC hierarchy.
//
// TIS_DESCENDANTS (generated by scripts/cwr/gen-tis-hierarchy.mjs from the MIT musicmetadata/territories
// data, a machine-readable copy of CISAC's TIS09-1540c hierarchy) maps each group/region TIS code to the
// leaf country codes it contains transitively — World ⊃ continents ⊃ regions ⊃ countries, plus the
// economic/political groups (EU, EEA, NAFTA, Commonwealth, …) and their members. Country codes expand to
// themselves. ~2019 snapshot; refresh by re-running the generator against a newer TIS export.

import { TIS_DESCENDANTS } from './tis-hierarchy-data';

const WORLD = 2136;

/** The leaf country codes a territory covers: a group → its members; a country → itself. */
export function expandTerritory(code: number): number[] {
  return TIS_DESCENDANTS[code] ?? [code];
}

/** Does `parent` strictly contain `child` — parent's coverage ⊇ child's, and parent ≠ child? */
export function tisContains(parent: number, child: number): boolean {
  if (parent === child) return false;
  const members = TIS_DESCENDANTS[parent];
  if (!members) return false; // a leaf country contains nothing
  const set = new Set(members);
  return expandTerritory(child).every((c) => set.has(c));
}

/** Do two territories' coverage intersect? Two INCLUDED territories that overlap double-claim the
 *  shared locations (World+USA, EU+France, EU+EEA, …). Symmetric. */
export function tisOverlaps(a: number, b: number): boolean {
  if (a === b) return false;
  const set = new Set(expandTerritory(a));
  return expandTerritory(b).some((c) => set.has(c));
}

export const TIS_WORLD = WORLD;
